AddCSLuaFile("GarrysModDeveloppementKit/cache/static.lua")
AddCSLuaFile("GarrysModDeveloppementKit/src/client/compile.lua")
AddCSLuaFile("GarrysModDeveloppementKit/src/client/gunit.lua")
AddCSLuaFile("GarrysModDeveloppementKit/event/cl_init.lua")
AddCSLuaFile("GarrysModDeveloppementKit/src/client/main.lua")
MsgC(Color(255,0,0),"@GarrysModDeveloppementKit",Color(0,255,0)," LOAD ",Color(255,0,255),"ressource\n")
