hook.Add("PreGamemodeLoaded","init the GarrysModDeveloppementKit preparation",function()
    include("GarrysModDeveloppementKit/src/server/ressource.lua")
    include("GarrysModDeveloppementKit/cache/static.lua")
    include("GarrysModDeveloppementKit/controller/core/server.lua")
    GarrysModDeveloppementKit.Core()
    include("GarrysModDeveloppementKit/connection/registre.lua")
end)
hook.Add("PostGamemodeLoaded","init the GarrysModDeveloppementKit Gunit and addons",function()
    include("GarrysModDeveloppementKit/src/server/gunit.lua")
    include("GarrysModDeveloppementKit/src/server/main.lua")
    MsgC(Color(255,0,0),"@GarrysModDeveloppementKit",Color(0,255,0)," have been charge since ",Color(0,200,255),"i like cheese\n")
end)
